name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.201"
      - name: Build
        run: dotnet build -c Release
